config/routes.rb
OnlineAuction::Application.routes.draw do
  
  devise_for :users

  namespace :admin do 
    resources :categories
    resources :items
    resources :lots
  end

  resources :lots, only: [:index, :show]
  resources :bets, only: [:create]
  

  root 'site#index'

  

end

app/models/bet.rb
class Bet < ActiveRecord::Base
  belongs_to :user
  belongs_to :lot

  after_create :increase_lot_expired_time, :user_bet_write_off

  private

  def increase_lot_expired_time
    self.lot.increase_expired_time
    self.lot.save!
  end

  def user_bet_write_off
    self.user.bet_write_off
    self.user.save!
  end
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many  :items
  has_ancestry
  validates :name, presence: true, uniqueness: true, length: { minimum:3 }
  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :items
  has_attached_file :item_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  has_many :lots
  has_many :images

  validates :name, :description, presence: true, length: { minimum: 3 }
  validates :description, length: { minimum: 30 }
  validates :price, presence: true,  numericality: { greater_than_or_equal_to: 1 }

  accepts_nested_attributes_for :images, :allow_destroy => true
 end

app/models/lot.rb
class Lot < ActiveRecord::Base
  belongs_to :item
  has_many :bets, dependent: :destroy

  validates :name, :description, :price, :time_step, :expired_time, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 1 }
  validates :description, length: { minimum: 30 }
  validates :name, length: { minimum: 3 }

  
  # Lot.all.select генерирует массив по условию, например Item.all.select { |item| item.price == 100 }

  # scope :active, -> { Lot.all.select { |lot| lot.active? } }
  # Lot.all.select { |lot| lot.active? }



  scope :active, -> { Lot.all.select { |lot| lot.active? } } 
  scope :finished, -> { Lot.all.select { |lot| lot.finished? } }
  scope :started, -> { Lot.all.select { |lot| lot.started? } }
  

  def active?
    started? && !finished?
  end

  def finished?
    Time.now.utc > self.expired_time
  end

  def started?
    Time.now.utc > self.start_time
  end
  
   # scope :started, ->  { where(Time.now.utc > self.start_time) }
   # scope :finished, -> { where(Time.now.utc > self.expired_time) }
   # scope :active, -> { where(started: true, finished: false) }

  def increase_expired_time
    self.expired_time += 30
    save!
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def bet_write_off
    self.bet -= 3
    self.save!
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  private

  # def only_for_admin
  #   redirect_to root_path unless current_user.admin?
  # end

  def check_admin
    render text: "У вас нет прав доступа к этой странице" unless current_user.admin?
    false
  end  
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  inherit_resources

  respond_to :html

  before_action :build_resource, only: [:index, :new]
  before_filter :set_category, except: [:index, :new, :create]

  private

  def set_category
    @category = Category.find(params[:id])
  end

  # def category_params
  #   params.require(:category).permit(:name, :picture, :parent_id)
  # end

  def build_resource_params
    [params.fetch(:category, {}).permit(:name, :picture, :parent_id)]
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::BaseController

  before_filter :set_item, except: [:index, :new, :create]

  def index
    @items = Item.all
  end

  def show
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_items_path
    else
      render "new"
    end
  end
  
  def new
    @item = Item.new
  end
  
  def edit
  end

  def update
    @item.update(item_params)

    redirect_to admin_items_path
  end

  def destroy
    @item.destroy
    redirect_to admin_items_path
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :description, :price, images_attributes: [:id, :item_image, :_destroy])
  end

end

app/controllers/admin/lots_controller.rb
class Admin::LotsController < Admin::BaseController

 before_filter :set_lot, except: [:index, :new, :create]

  def index
    @lots = Lot.all
  end

  def new
    # @items = Item.all
    @lot = Lot.new
  end

  def create
    @lot = Lot.new(lot_params)
    if @lot.save
      redirect_to admin_lots_path
    else
      render "new"
    end
  end

  def destroy
    @lot.destroy
    redirect_to admin_lots_path
  end

  def show
  end

  def edit
  end

  def update
    @lot.update(lot_params)

    redirect_to admin_lots_path
  end

  def set_lot
    @lot = Lot.find(params[:id])
  end
  
  private

  def lot_params
   params.require(:lot).permit(:name, :description, :price, :start_time, :expired_time, :time_step, :item_id)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:login, :email, :password, :nickname, :first_name, :last_name) }
  end
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  #  нужен js для обработки ответа от девайза
  # before_filter :authenticate_user!

  respond_to :js
  # def create
  #   @lot = Lot.find(params[:lot_id])
  #   @bet = @lot.bets.build
  #   if @bet.save
  #     @lot.update(expired_time: @lot.expired_time + @lot.time_step.minutes)
  #     redirect_to lot_path(@lot)
  #   else
  #     redirect_to lot_path(@lot)
  #   end
  # end
  
  def create
    @user = current_user
    @lot = Lot.find(params[:lot_id])
    @bet = Bet.create(lot: @lot, user: @user)
    PrivatePub.publish_to "/lots/update", lot_id: @bet.lot.id, expired_time: @bet.lot.expired_time.to_s
    render nothing: true
  end

  private

  def bet_params
    params.require(:bet).permit(:lot_id, :user_id) if params[:bet]
  end
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController

  def index
    @lots = Lot.all
    @finished_lots = Lot.finished
    @active_lots = Lot.active
    @started_lots = Lot.started

  end

  def show
    @lot = Lot.find(params[:id])
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/lots_helper.rb
module Admin::LotsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/lots_helper.rb
module LotsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/admin/categories/_form.html.haml
=simple_form_for [:admin, @category] do |f|

  %p
    = f.input :name
  %p
    = f.input :picture, label: "Picture"
  %p
    = f.label "Parent"
    = f.collection_select :parent_id, Category.order(:name), :id, :name, { include_blank: true }
  %p
    = f.submit "Save"

app/views/admin/categories/edit.html.haml
%p Add a new Category
=render :partial => "form"

app/views/admin/categories/index.html.haml
.navbar
  .navbar-inner
    %a.brand{ href: admin_categories_path } Categories
    %ul.nav
      %li
        %a{ href: new_admin_category_path } New Category
      %a.brand{ href: admin_items_path } Items
      %a.brand{ href: admin_lots_path } Lots
      %li
        = link_to "Выйти", destroy_user_session_path, method: :delete

%h1{ :align => "center" }>Categories
- @categories.each do |category|
  %div{ padding: 10 }[category]
    %b Name
    = link_to category.name, admin_category_path(category)
    %br
    %b
    = category.parent.name if category.parent
    %br
    .controls
    = link_to "Edit", edit_admin_category_path(category)
    = link_to "Delete", admin_category_path(category), :method => :delete, :confirm => "Are u shure?"  

app/views/admin/categories/new.html.haml
%p Add a new Category
=render :partial => "form"

app/views/admin/categories/show.html.haml
%h1= @category.name
= @category.picture.presence ? image_tag(@category.picture.url(:medium)) : image_tag("no_image.jpg")
/ =image_tag @category.picture.url(:thumb)
%p
= @category.parent.name if @category.parent

app/views/admin/items/_form.html.haml
d= simple_nested_form_for [:admin, @item], :html => { :multipart => true } do |f|
  %p
    = f.input :name
  %p
    = f.input :description
  %p
    = f.input :price
  
  %p
  = f.fields_for :images do |image|
    - unless image.object.new_record?
      = image_tag image.object.item_image.url(:medium)
    - else
      = image.file_field :item_image
    = image.link_to_remove "Remove"
  = f.link_to_add "Add image", :images
  %p
    =f.submit "Save"

app/views/admin/items/edit.html.haml
%p Add a new Item
=render :partial => "form"

app/views/admin/items/index.html.haml
.navbar
  .navbar-inner
    %a.brand{ href: admin_items_path } Items
    %ul.nav
      %li
        %a{ href: new_admin_item_path } New Item
      %a.brand{ href: admin_categories_path } Categories
      %li
        = link_to "Выйти", destroy_user_session_path, method: :delete

%h1{ :align => "center" }>Items
- @items.each do |item|
  %div{ padding: 10 }[item]
    %b Name
    = link_to item.name, admin_item_path(item)
    %br
    %b
    / = category.parent.name if category.parent
    %br
    .controls
    = link_to "Edit", edit_admin_item_path(item)
    = link_to "Delete", admin_item_path(item), :method => :delete, :confirm => "Are u shure?"  

app/views/admin/items/new.html.haml
%p Add a new Item
=render :partial => "form"

app/views/admin/items/show.html.haml
%h1= @item.name

%p=@item.description
%p=@item.price
-@item.images.each do |i|
  %p=image_tag i.item_image.url(:medium)
/=image_tag @category.picture.url(:medium)

app/views/admin/lots/_form.html.haml
= simple_nested_form_for [:admin, @lot], :html => { :multipart => true } do |f|
  %p
    = f.input :name
  %p
    = f.input :description
  %p
    = f.input :price
  %p
    = f.input :start_time  
  %p
    = f.input :expired_time
  %p
    = f.input :time_step
  %p
    = f.association :item
  %p
    =f.submit "Save"

app/views/admin/lots/edit.html.haml
%p Add a new Lot
=render :partial => "form"

app/views/admin/lots/index.html.haml
.navbar
  .navbar-inner
    %a.brand{ href: admin_lots_path } Lots
    %ul.nav
      %li
        %a{ href: new_admin_lot_path } New Lot
      %a.brand{ href: admin_categories_path } Categories
      %li
        = link_to "Выйти", destroy_user_session_path, method: :delete

%h1{ :align => "center" }>Lots
- @lots.each do |lot|
  %div{ padding: 10 }[lot]
    %b Name
    = link_to lot.name, admin_lot_path(lot)
    %br
    %b
    %br
    .controls
    = link_to "Edit", edit_admin_lot_path(lot)
    = link_to "Delete", admin_lot_path(lot), :method => :delete, :confirm => "Are u shure?"  

app/views/admin/lots/new.html.haml
%p Add a new Lot
= render :partial => "form"

app/views/admin/lots/show.html.haml
.lot 
  %h1
    = @lot.name
  %h2
    = @lot.price
  %h4
    = @lot.start_time
  %h4
    = @lot.expired_time

app/views/lots/index.html.haml
%h2{ :align => "center" }>Активные Лоты
- @active_lots.each do |lot|
  %div{ padding: 10 }[lot]
    = link_to lot.name, lot_path(lot)
    %br
%hr
%h2{ :align => "center" }>Завершившиеся Лоты
- @finished_lots.each do |lot|
  %div{ padding: 10 }[lot]
    = link_to lot.name, lot_path(lot)
    %br

app/views/lots/show.html.haml
.lot{id: "lot_#{@lot.id}"}
  %h1
    = @lot.name
  %h3
    = @lot.price
  %p
    =@lot.start_time
  %p.expired_time
    =@lot.expired_time

  %p
    -@lot.item.images.each do |i|
      =image_tag i.item_image.url(:medium)
  / -@item.images.each do |i|
  / %p=image_tag i.item_image.url(:medium)

-unless @lot.finished?
  =button_to 'Make a Bet!', bets_path(lot_id: @lot), remote: true

Ставки:
=current_user.bet
=subscribe_to "/lots/update"

app/views/site/index.html.haml
%h1 Hello
= link_to "Admin panel", admin_categories_path
%p
= link_to "Выйти", destroy_user_session_path, method: :delete